server:
    address: localhost
    port: 8080
spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/membermanager?createDatabaseIfNotExist=true&useUnicode=true&characterEnconding=UTF-8
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true